"""scheme corpus tables

Revision ID: 8abb2947b3e7
Revises: 
Create Date: 2026-09-11 16:44:52.036096

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8abb2947b3e7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.String(length=160), nullable=False),
    sa.Column('myscheme_id', sa.String(length=48), nullable=True),
    sa.Column('scheme_name', sa.Text(), nullable=False),
    sa.Column('scheme_short_title', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('states', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('subcategories', postgresql.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('nodal_ministry', sa.Text(), nullable=True),
    sa.Column('nodal_department', sa.Text(), nullable=True),
    sa.Column('implementing_agency', sa.Text(), nullable=True),
    sa.Column('scheme_for', sa.String(length=60), nullable=True),
    sa.Column('target_beneficiaries', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('dbt_scheme', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('benefits_md', sa.Text(), nullable=True),
    sa.Column('exclusions_md', sa.Text(), nullable=True),
    sa.Column('eligibility_description', sa.Text(), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benefit_types', postgresql.ARRAY(sa.String(length=60)), nullable=True),
    sa.Column('documents_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('application_process', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheme_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('application_modes', postgresql.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('helpline', sa.Text(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('income_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gender', postgresql.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('caste', postgresql.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('disability', sa.Boolean(), nullable=True),
    sa.Column('bpl_card', sa.Boolean(), nullable=True),
    sa.Column('state_residence', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('minority', sa.Boolean(), nullable=True),
    sa.Column('student', sa.Boolean(), nullable=True),
    sa.Column('marital_status', postgresql.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('scheme_open_date', sa.Date(), nullable=True),
    sa.Column('scheme_close_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id')
    )
    op.create_index('ix_schemes_categories_gin', 'schemes', ['categories'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_content_hash'), 'schemes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_schemes_level'), 'schemes', ['level'], unique=False)
    op.create_index(op.f('ix_schemes_state'), 'schemes', ['state'], unique=False)
    op.create_index('ix_schemes_state_category', 'schemes', ['state', 'category'], unique=False)
    op.create_index('ix_schemes_states_gin', 'schemes', ['states'], unique=False, postgresql_using='gin')
    op.create_index('ix_schemes_tags_gin', 'schemes', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('scheme_embedding_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_pk', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_pk'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_pk', 'model', name='uq_scheme_embedding_model')
    )
    op.create_table('scheme_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_pk', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('scheme_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('benefits_md', sa.Text(), nullable=True),
    sa.Column('eligibility_description', sa.Text(), nullable=True),
    sa.Column('documents_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_pk'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_pk', 'lang', name='uq_scheme_translation_lang')
    )
    op.create_index(op.f('ix_scheme_translations_scheme_pk'), 'scheme_translations', ['scheme_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_translations_scheme_pk'), table_name='scheme_translations')
    op.drop_table('scheme_translations')
    op.drop_table('scheme_embedding_state')
    op.drop_index('ix_schemes_tags_gin', table_name='schemes', postgresql_using='gin')
    op.drop_index('ix_schemes_states_gin', table_name='schemes', postgresql_using='gin')
    op.drop_index('ix_schemes_state_category', table_name='schemes')
    op.drop_index(op.f('ix_schemes_state'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_level'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_content_hash'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_index('ix_schemes_categories_gin', table_name='schemes', postgresql_using='gin')
    op.drop_table('schemes')
    # ### end Alembic commands ###
