"""otp challenges and refresh tokens

P3 slice 2: phone-OTP login on top of the anonymous identity from slice 1.

Neither table stores the secret it checks — `code_hash` is an HMAC of the code and
`token_hash` a digest of the token — so this migration adds no new plaintext
credential to the database. See `models/auth.py` for why, and for what `family_id`
plus `used_at` buy.

`refresh_tokens.user_id` cascades on delete, which is what makes `DELETE /api/me`
complete rather than orphaning credentials that still name an erased user.

Revision ID: cacb34a0294d
Revises: 7b8bad407fe3
Create Date: 2026-09-14 13:55:26.203255

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cacb34a0294d'
down_revision: str | None = '7b8bad407fe3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_e164', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_expires', 'otp_challenges', ['expires_at'], unique=False)
    op.create_index('ix_otp_phone_created', 'otp_challenges', ['phone_e164', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_family_revoked', 'refresh_tokens', ['family_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_family_revoked', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_otp_phone_created', table_name='otp_challenges')
    op.drop_index('ix_otp_expires', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
