"""users table with anonymous identity and turn quota

Revision ID: 7b8bad407fe3
Revises: 8abb2947b3e7
Create Date: 2026-09-14 12:54:15.534749

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7b8bad407fe3'
down_revision: str | None = '8abb2947b3e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anon_id', sa.String(length=36), nullable=True),
    sa.Column('phone_e164', sa.String(length=16), nullable=True),
    sa.Column('consent_version', sa.String(length=16), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turns_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quota_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anon_id IS NOT NULL OR phone_e164 IS NOT NULL', name='ck_users_has_identity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_index('ix_users_quota_window', 'users', ['quota_window_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_quota_window', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
