"""profiles, conversations, messages, interactions, eligibility cache

Revision ID: 13fb69cbd772
Revises: cacb34a0294d
Create Date: 2026-09-14 14:42:00.687157

P3 slice 3 — the five tables the plan's memory model needs.

Three things about the shape are deliberate and would be easy to "fix" into
something wrong:

* **`payload`, `body` and `reasons` are `LargeBinary`, not `jsonb`.** Everything
  personal is sealed with AES-256-GCM before it reaches the database
  (`auth/crypto.py`), which is the DPDP encryption-at-rest requirement. The cost
  is that those columns cannot be filtered, indexed, ordered or aggregated — and
  it costs nothing here, because a profile is read whole by primary key for one
  user and the rules run in Python. `eligible` stays in the clear precisely so
  the one thing that *is* aggregated can be.
* **`scheme_interactions.scheme_id` and `.conversation_id` are plain strings with
  no foreign key.** The scheme id because a de-listed scheme should not take a
  year of interaction history with it, and the conversation id because
  interactions are retained for 365 days while transcripts expire at 90 — a real
  FK with `ON DELETE CASCADE` would silently drag the longer window down to the
  shorter one, and `SET NULL` would lose the attribution.
* **One index per table, and no more.** Both cover the only query that exists
  (`user_id` plus a time), `messages` rides the leading column of
  `uq_messages_seq`, and `eligibility_evaluations` is served by its composite
  primary key. Slice 2 shipped an index nothing ever used; this is the correction.

Nothing here backfills, and nothing here is destructive: five new tables, all
cascading from `users`, so `DELETE /api/me` keeps working with no changes.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '13fb69cbd772'
down_revision: str | None = 'cacb34a0294d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=24), nullable=True),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_started', 'conversations', ['user_id', 'started_at'], unique=False)
    op.create_table('eligibility_evaluations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scheme_id', sa.String(length=160), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.LargeBinary(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'scheme_id')
    )
    op.create_table('scheme_interactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scheme_id', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_user_created', 'scheme_interactions', ['user_id', 'created_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('consent_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_messages_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('user_profiles')
    op.drop_index('ix_interactions_user_created', table_name='scheme_interactions')
    op.drop_table('scheme_interactions')
    op.drop_table('eligibility_evaluations')
    op.drop_index('ix_conversations_user_started', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
